/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FoodEntryInput = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'servingSize' : IDL.Float64,
  'foodName' : IDL.Text,
  'protein' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductDetails = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RunningSession = IDL.Record({
  'duration' : IDL.Nat,
  'userId' : IDL.Principal,
  'distance' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'runId' : IDL.Nat,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'uploadTimestamp' : IDL.Int,
  'commentCount' : IDL.Nat,
  'uploaderId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const FoodEntry = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'userId' : IDL.Principal,
  'calories' : IDL.Float64,
  'servingSize' : IDL.Float64,
  'timestamp' : IDL.Int,
  'foodName' : IDL.Text,
  'protein' : IDL.Float64,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'userId' : UserId,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isInternal' : IDL.Bool,
  'quantity' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'videoId' : IDL.Nat,
});
export const Workout = IDL.Record({
  'weight' : IDL.Nat,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'exerciseName' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addFoodEntry' : IDL.Func([FoodEntryInput], [IDL.Nat], []),
  'addProduct' : IDL.Func([ProductDetails], [], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteFoodEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteRunningSession' : IDL.Func([IDL.Nat], [], []),
  'editFoodEntry' : IDL.Func([IDL.Nat, FoodEntryInput], [], []),
  'editProduct' : IDL.Func([ProductId, ProductDetails], [], []),
  'fetchExternalProducts' : IDL.Func([], [IDL.Text], []),
  'getAllRunningSessions' : IDL.Func([], [IDL.Vec(RunningSession)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFoodEntry' : IDL.Func([IDL.Nat], [IDL.Opt(FoodEntry)], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getRunningSession' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RunningSession)],
      ['query'],
    ),
  'getUserFoodEntries' : IDL.Func([], [IDL.Vec(FoodEntry)], ['query']),
  'getUserFoodEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRunningSessions' : IDL.Func([], [IDL.Vec(RunningSession)], ['query']),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
  'getVideoComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getVideoLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'hasLikedVideo' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Nat], [], []),
  'logRunningSession' : IDL.Func(
      [IDL.Float64, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'logWorkout' : IDL.Func([Workout], [], []),
  'placeOrder' : IDL.Func([IDL.Text], [OrderId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
  'uploadVideo' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FoodEntryInput = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'servingSize' : IDL.Float64,
    'foodName' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductDetails = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RunningSession = IDL.Record({
    'duration' : IDL.Nat,
    'userId' : IDL.Principal,
    'distance' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'runId' : IDL.Nat,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'uploadTimestamp' : IDL.Int,
    'commentCount' : IDL.Nat,
    'uploaderId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const FoodEntry = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'userId' : IDL.Principal,
    'calories' : IDL.Float64,
    'servingSize' : IDL.Float64,
    'timestamp' : IDL.Int,
    'foodName' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'userId' : UserId,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isInternal' : IDL.Bool,
    'quantity' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'videoId' : IDL.Nat,
  });
  const Workout = IDL.Record({
    'weight' : IDL.Nat,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'exerciseName' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addFoodEntry' : IDL.Func([FoodEntryInput], [IDL.Nat], []),
    'addProduct' : IDL.Func([ProductDetails], [], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteFoodEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteRunningSession' : IDL.Func([IDL.Nat], [], []),
    'editFoodEntry' : IDL.Func([IDL.Nat, FoodEntryInput], [], []),
    'editProduct' : IDL.Func([ProductId, ProductDetails], [], []),
    'fetchExternalProducts' : IDL.Func([], [IDL.Text], []),
    'getAllRunningSessions' : IDL.Func(
        [],
        [IDL.Vec(RunningSession)],
        ['query'],
      ),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFoodEntry' : IDL.Func([IDL.Nat], [IDL.Opt(FoodEntry)], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getRunningSession' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RunningSession)],
        ['query'],
      ),
    'getUserFoodEntries' : IDL.Func([], [IDL.Vec(FoodEntry)], ['query']),
    'getUserFoodEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRunningSessions' : IDL.Func(
        [],
        [IDL.Vec(RunningSession)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
    'getVideoComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getVideoLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'hasLikedVideo' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Nat], [], []),
    'logRunningSession' : IDL.Func(
        [IDL.Float64, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'logWorkout' : IDL.Func([Workout], [], []),
    'placeOrder' : IDL.Func([IDL.Text], [OrderId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
    'uploadVideo' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };