/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArticleId = bigint;
export interface ArticleSummary {
  'id' : ArticleId,
  'title' : string,
  'articleType' : ArticleType,
  'author' : string,
  'featuredImageUrl' : string,
  'publicationDate' : bigint,
  'category' : NewsCategory,
}
export type ArticleType = { 'internal' : null } |
  { 'external' : null };
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Comment {
  'id' : bigint,
  'userId' : Principal,
  'text' : string,
  'timestamp' : bigint,
  'videoId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FoodEntry {
  'id' : bigint,
  'fat' : number,
  'carbs' : number,
  'userId' : Principal,
  'calories' : number,
  'servingSize' : number,
  'timestamp' : bigint,
  'foodName' : string,
  'protein' : number,
}
export interface FoodEntryInput {
  'fat' : number,
  'carbs' : number,
  'calories' : number,
  'servingSize' : number,
  'foodName' : string,
  'protein' : number,
}
export interface NewsArticle {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'articleType' : ArticleType,
  'creationTimestamp' : bigint,
  'creatorUserId' : UserId,
  'author' : string,
  'featuredImageUrl' : string,
  'publicationDate' : bigint,
  'category' : NewsCategory,
  'externalUrl' : [] | [string],
}
export type NewsCategory = { 'trainingAdvice' : null } |
  { 'productReviews' : null } |
  { 'fitnessLifestyle' : null } |
  { 'mentalHealth' : null } |
  { 'sportsNews' : null } |
  { 'workoutTips' : null } |
  { 'nutrition' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : UserId,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
}
export type OrderId = bigint;
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'isInternal' : boolean,
  'quantity' : bigint,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export type ProductId = bigint;
export interface RunningSession {
  'duration' : bigint,
  'userId' : Principal,
  'distance' : number,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'runId' : bigint,
}
export interface SearchResult {
  'itemId' : bigint,
  'title' : string,
  'contentType' : string,
  'relevanceScore' : number,
  'previewText' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'likeCount' : bigint,
  'description' : string,
  'videoFile' : ExternalBlob,
  'uploadTimestamp' : bigint,
  'commentCount' : bigint,
  'uploaderId' : Principal,
}
export interface Workout {
  'weight' : bigint,
  'reps' : bigint,
  'sets' : bigint,
  'exerciseName' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFoodEntry' : ActorMethod<[bigint], undefined>,
  'deleteRunningSession' : ActorMethod<[bigint], undefined>,
  'editFoodEntry' : ActorMethod<[bigint, FoodEntryInput], undefined>,
  'fetchExternalProducts' : ActorMethod<[], string>,
  'fetchExternalSportsProducts' : ActorMethod<
    [[] | [string], [] | [string]],
    string
  >,
  'fetchSportsAndFitnessVideos' : ActorMethod<[], string>,
  'getAllArticlesSortedByPublicationDate' : ActorMethod<[], Array<NewsArticle>>,
  'getAllNewsArticles' : ActorMethod<[[] | [NewsCategory]], Array<NewsArticle>>,
  'getAllRunningSessions' : ActorMethod<[], Array<RunningSession>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getArticleSummaries' : ActorMethod<[], Array<ArticleSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExternalFitnessSearchResults' : ActorMethod<[string], string>,
  'getFoodEntry' : ActorMethod<[bigint], [] | [FoodEntry]>,
  'getNewsArticle' : ActorMethod<[ArticleId], [] | [NewsArticle]>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getRunningSession' : ActorMethod<[bigint], [] | [RunningSession]>,
  'getUserFoodEntries' : ActorMethod<[], Array<FoodEntry>>,
  'getUserFoodEntryCount' : ActorMethod<[], bigint>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRunningSessions' : ActorMethod<[], Array<RunningSession>>,
  'getVideoComments' : ActorMethod<[bigint], Array<Comment>>,
  'getVideoLikeCount' : ActorMethod<[bigint], bigint>,
  'getWorkouts' : ActorMethod<[], Array<Workout>>,
  'hasLikedVideo' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logRunningSession' : ActorMethod<[number, bigint, [] | [string]], bigint>,
  'logWorkout' : ActorMethod<[Workout], undefined>,
  'placeOrder' : ActorMethod<[string], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchContent' : ActorMethod<[string], Array<SearchResult>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadVideo' : ActorMethod<[string, string, ExternalBlob], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];